version: '3.7'
services:
  backend:
    #image: todo-backend:0.0.1-SNAPSHOT
    build: .
    container_name: todo-backend
    ports:
      - "8080:8080"
    networks:
      - default
    environment:
      - MONGO_URI=todo-mongo
      - MONGO_PORT=27017
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6
    container_name: todo-mongo
    ports:
      - "27017:27017"
